import os
import uuid
import shutil
import json
from contextlib import asynccontextmanager
from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.responses import JSONResponse
from fastapi.middleware.cors import CORSMiddleware
import uvicorn

# Import the compiled LangGraph agent
from graph import agent_graph, AgentState

# Define base directories for uploads and reports
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
UPLOADS_DIR = os.path.join(BASE_DIR, "uploads")
REPORTS_DIR = os.path.join(BASE_DIR, "reports")


def format_response_markdown(final_state, filename):
    """
    Format the agentic workflow response into markdown for frontend display.
    """
    # Extract data from final state
    project_context = final_state.get("project_context", "")
    test_scaffolding = final_state.get("test_scaffolding", "{}")
    execution_results = final_state.get("execution_results", "")
    intended_behaviors = final_state.get("intended_behaviors", [])
    validated_behaviors = final_state.get("validated_behaviors", [])
    semantic_gaps = final_state.get("semantic_gaps", [])
    report = final_state.get("report", "")
    suggestions = final_state.get("suggestions", "")

    # Parse test scaffolding JSON if it exists
    try:
        scaffolding_data = json.loads(test_scaffolding) if test_scaffolding else {}
    except json.JSONDecodeError:
        scaffolding_data = {}

    # Extract language and files from scaffolding
    language = scaffolding_data.get("language", "Unknown")
    file_setup = scaffolding_data.get("file_setup", {})
    files = file_setup.get("files", {})
    run_command = scaffolding_data.get("run_command", "N/A")

    # Create comprehensive markdown response
    markdown_content = f"""# 🧪 Agentic Testing Analysis Report

## 📁 File Information
- **Filename**: `{filename}`
- **Language Detected**: `{language}`
- **Analysis Date**: {uuid.uuid4().hex[:8]}

---

## 📋 Stage 1: Project Context Analysis

### Source Code Analyzed:
```{language.lower() if language != 'Unknown' else 'text'}
{project_context[:1000]}{'...' if len(project_context) > 1000 else ''}
```

---

## 🔧 Stage 2: Test Generation

### Generated Test Files:
"""

    # Add generated files to markdown
    if files:
        for filename_key, content in files.items():
            if content and content.strip():
                # Determine file type for syntax highlighting
                file_ext = (
                    filename_key.split(".")[-1].lower()
                    if "." in filename_key
                    else "text"
                )

                markdown_content += f"""
#### 📄 `{filename_key}`
```{file_ext}
{content}
```
"""
    else:
        markdown_content += "\n*No test files were generated.*\n"

    markdown_content += f"""
### 🚀 Run Command:
```bash
{run_command}
```

---

## ⚡ Stage 3: Test Execution Results

```text
{execution_results}
```

---

## 🧠 Stage 4: Semantic Test Adequacy (STAR)

### Intended Behaviors:
{"\n".join(f"- {item}" for item in intended_behaviors) if intended_behaviors else "*None detected*"}

### Validated Behaviors:
{"\n".join(f"- {item}" for item in validated_behaviors) if validated_behaviors else "*None detected*"}

### Semantic Gaps:
{"\n".join(f"- {item}" for item in semantic_gaps) if semantic_gaps else "*None detected*"}

---

## 📊 Stage 5: Analysis Report

{report if report else "*No analysis report available.*"}

---

## 💡 Stage 6: Improvement Suggestions

{suggestions if suggestions else "*No suggestions available.*"}

---

## 📈 Summary

- **Language**: {language}
- **Files Generated**: {len(files)} file(s)
- **Execution Status**: {'✅ Completed' if execution_results else '❌ Failed'}
- **Report Status**: {'✅ Generated' if report else '❌ Not Generated'}
- **Suggestions Status**: {'✅ Available' if suggestions else '❌ Not Available'}

---
*Generated by Mr. Testacular - Agentic Testing Solution*
"""

    return {
        "success": True,
        "filename": filename,
        "language": language,
        "stages": {
            "project_analysis": {
                "title": "📋 Project Context Analysis",
                "content": f"```{language.lower() if language != 'Unknown' else 'text'}\n{project_context}\n```",
                "status": "completed" if project_context else "failed",
            },
            "test_generation": {
                "title": "🔧 Test Generation",
                "content": format_test_files_markdown(files, run_command),
                "status": "completed" if files else "failed",
                "files_count": len(files),
            },
            "test_execution": {
                "title": "⚡ Test Execution",
                "content": f"```text\n{execution_results}\n```",
                "status": "completed" if execution_results else "failed",
            },
            "semantic_test_adequacy": {
                "title": "🧠 Semantic Test Adequacy (STAR)",
                "content": (
                    "### Intended Behaviors:\n"
                    + (
                        "\n".join(f"- {item}" for item in intended_behaviors)
                        if intended_behaviors
                        else "*None detected*"
                    )
                    + "\n\n### Validated Behaviors:\n"
                    + (
                        "\n".join(f"- {item}" for item in validated_behaviors)
                        if validated_behaviors
                        else "*None detected*"
                    )
                    + "\n\n### Semantic Gaps:\n"
                    + (
                        "\n".join(f"- {item}" for item in semantic_gaps)
                        if semantic_gaps
                        else "*None detected*"
                    )
                ),
                "status": "completed",
            },
            "analysis_report": {
                "title": "📊 Analysis Report",
                "content": report if report else "*No analysis report available.*",
                "status": "completed" if report else "failed",
            },
            "suggestions": {
                "title": "💡 Improvement Suggestions",
                "content": (
                    suggestions if suggestions else "*No suggestions available.*"
                ),
                "status": "completed" if suggestions else "failed",
            },
        },
        "full_markdown": markdown_content,
        "raw_data": {
            "project_context": project_context,
            "test_scaffolding": test_scaffolding,
            "execution_results": execution_results,
            "intended_behaviors": intended_behaviors,
            "validated_behaviors": validated_behaviors,
            "semantic_gaps": semantic_gaps,
            "report": report,
            "suggestions": suggestions,
        },
    }


def format_test_files_markdown(files, run_command):
    """Format test files into markdown."""
    if not files:
        return "*No test files were generated.*"

    markdown = f"### Generated Test Files ({len(files)} files):\n\n"

    for filename, content in files.items():
        if content and content.strip():
            file_ext = filename.split(".")[-1].lower() if "." in filename else "text"
            markdown += f"#### 📄 `{filename}`\n```{file_ext}\n{content}\n```\n\n"

    markdown += f"### 🚀 Run Command:\n```bash\n{run_command}\n```\n"
    return markdown


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Ensure necessary directories exist on server startup."""
    os.makedirs(UPLOADS_DIR, exist_ok=True)
    os.makedirs(REPORTS_DIR, exist_ok=True)
    yield


# Initialize FastAPI app
api = FastAPI(
    title="Agentic Testing Solution API",
    description="Upload a zipped project or a single code file (any language), and an agentic workflow will generate, execute, and analyze tests.",
    version="1.2.0",
    lifespan=lifespan,
)

api.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@api.get("/health")
async def health_check():
    """Simple health check endpoint."""
    return JSONResponse(
        status_code=200, content={"status": "ok", "message": "API is running"}
    )


@api.post("/test-project/")
async def test_project_endpoint(file: UploadFile = File(...)):
    """
    Endpoint to upload a zipped project or a single code file, run the testing workflow, and return the result.
    """
    # Relaxed file check to allow any code file or zip archive.
    if not file.filename or "." not in file.filename:
        raise HTTPException(
            status_code=400,
            detail="Invalid file. Please upload a file with an extension.",
        )

    # Create a unique directory for this request to avoid conflicts
    session_id = str(uuid.uuid4())
    session_dir = os.path.join(UPLOADS_DIR, session_id)
    os.makedirs(session_dir)

    file_path = os.path.join(session_dir, file.filename)

    try:
        # 1. Save the uploaded file
        with open(file_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)

        # 2. Define the initial state for the LangGraph
        initial_state: AgentState = {
            "file_path": file_path,
            "project_context": None,
            "test_scaffolding": None,
            "execution_results": None,
            "intended_behaviors": None,
            "validated_behaviors": None,
            "semantic_gaps": None,
            "fault_classifications": None,
            "report": None,
            "suggestions": None,
            "iteration": 0,
        }

        # 3. Invoke the agentic graph
        final_state = agent_graph.invoke(initial_state)

        # (Iteration is handled implicitly by LangGraph state updates.)

        # 4. Format all outputs in markdown for frontend display
        formatted_response = format_response_markdown(final_state, file.filename)

        return JSONResponse(content=formatted_response)

    except Exception as e:
        # Log the exception for debugging
        print(f"An error occurred: {e}")
        raise HTTPException(status_code=500, detail=str(e))

    finally:
        # 5. Clean up the temporary session directory
        if os.path.exists(session_dir):
            shutil.rmtree(session_dir)


if __name__ == "__main__":
    # To run the server: uvicorn main:api --reload
    uvicorn.run(api, host="0.0.0.0", port=8000)
